services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend